// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kiichain/rewards/v1beta1/types.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RewardPool is the global fee pool for distribution.
type RewardPool struct {
	CommunityPool github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,1,rep,name=community_pool,json=communityPool,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"community_pool"`
	// Timestamp of the last emission release
	LastReleaseTime time.Time `protobuf:"bytes,2,opt,name=last_release_time,json=lastReleaseTime,proto3,stdtime" json:"last_release_time" yaml:"last_release_time"`
	// Cumulative amount released from the pool (observability only)
	TotalReleased types.Coin `protobuf:"bytes,3,opt,name=total_released,json=totalReleased,proto3" json:"total_released" yaml:"total_released"`
}

func (m *RewardPool) Reset()         { *m = RewardPool{} }
func (m *RewardPool) String() string { return proto.CompactTextString(m) }
func (*RewardPool) ProtoMessage()    {}
func (*RewardPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_890c6773eb163743, []int{0}
}
func (m *RewardPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardPool.Merge(m, src)
}
func (m *RewardPool) XXX_Size() int {
	return m.Size()
}
func (m *RewardPool) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardPool.DiscardUnknown(m)
}

var xxx_messageInfo_RewardPool proto.InternalMessageInfo

func (m *RewardPool) GetCommunityPool() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.CommunityPool
	}
	return nil
}

func (m *RewardPool) GetLastReleaseTime() time.Time {
	if m != nil {
		return m.LastReleaseTime
	}
	return time.Time{}
}

func (m *RewardPool) GetTotalReleased() types.Coin {
	if m != nil {
		return m.TotalReleased
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*RewardPool)(nil), "kiichain.rewards.v1beta1.RewardPool")
}

func init() {
	proto.RegisterFile("kiichain/rewards/v1beta1/types.proto", fileDescriptor_890c6773eb163743)
}

var fileDescriptor_890c6773eb163743 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xbf, 0xae, 0xd3, 0x30,
	0x18, 0xc5, 0x93, 0x56, 0x62, 0x48, 0xd5, 0xa2, 0x56, 0x20, 0x85, 0x0a, 0x92, 0x2a, 0xea, 0x50,
	0xf1, 0xc7, 0x56, 0xcb, 0x82, 0x18, 0x0b, 0x62, 0x46, 0x11, 0x13, 0x4b, 0xe4, 0x24, 0x26, 0xb5,
	0x6a, 0xe7, 0x8b, 0x62, 0x17, 0xe8, 0xc0, 0x3b, 0xf4, 0x31, 0x10, 0x13, 0x8f, 0xd1, 0xb1, 0x23,
	0x62, 0x68, 0x51, 0x3b, 0xb0, 0xdf, 0x27, 0xb8, 0x8a, 0xe3, 0x44, 0xf7, 0xea, 0xde, 0x25, 0xf9,
	0x72, 0x74, 0x4e, 0xce, 0xf7, 0xb3, 0xec, 0x4c, 0xd7, 0x8c, 0x25, 0x2b, 0xc2, 0x72, 0x5c, 0xd2,
	0x6f, 0xa4, 0x4c, 0x25, 0xfe, 0x3a, 0x8f, 0xa9, 0x22, 0x73, 0xac, 0xb6, 0x05, 0x95, 0xa8, 0x28,
	0x41, 0xc1, 0xc8, 0x6d, 0x5c, 0xc8, 0xb8, 0x90, 0x71, 0x8d, 0xbd, 0x04, 0xa4, 0x00, 0x89, 0x63,
	0x22, 0x69, 0x1b, 0x4d, 0x80, 0xe5, 0x75, 0x72, 0xfc, 0x28, 0x83, 0x0c, 0xf4, 0x88, 0xab, 0xc9,
	0xa8, 0x7e, 0x06, 0x90, 0x71, 0x8a, 0xf5, 0x57, 0xbc, 0xf9, 0x82, 0x15, 0x13, 0x54, 0x2a, 0x22,
	0x0a, 0x63, 0x18, 0x12, 0xc1, 0x72, 0xc0, 0xfa, 0x59, 0x4b, 0xc1, 0xdf, 0x8e, 0xe3, 0x84, 0xba,
	0xfd, 0x23, 0x00, 0x1f, 0xfd, 0x70, 0x06, 0x09, 0x08, 0xb1, 0xc9, 0x99, 0xda, 0x46, 0x05, 0x00,
	0x77, 0xed, 0x49, 0x77, 0xd6, 0x5b, 0x3c, 0x45, 0xf5, 0x46, 0xa8, 0xda, 0xa8, 0x59, 0x13, 0xbd,
	0xa7, 0xc9, 0x3b, 0x60, 0xf9, 0xf2, 0xcd, 0xfe, 0xe8, 0x5b, 0xbf, 0x4e, 0xfe, 0x8b, 0x8c, 0xa9,
	0xd5, 0x26, 0x46, 0x09, 0x08, 0x6c, 0x08, 0xea, 0xd7, 0x2b, 0x99, 0xae, 0x0d, 0xba, 0xc9, 0xc8,
	0x9f, 0xff, 0x7f, 0x3f, 0xb7, 0xc3, 0x7e, 0xdb, 0xa6, 0xeb, 0xb9, 0x33, 0xe4, 0x44, 0xaa, 0xa8,
	0xa4, 0x9c, 0x12, 0x49, 0xa3, 0x0a, 0xc0, 0xed, 0x4c, 0xec, 0x59, 0x6f, 0x31, 0x46, 0x35, 0x1d,
	0x6a, 0xe8, 0xd0, 0xa7, 0x86, 0x6e, 0x39, 0xad, 0xfa, 0xaf, 0x8e, 0xbe, 0xbb, 0x25, 0x82, 0xbf,
	0x0d, 0xee, 0xfc, 0x22, 0xd8, 0x9d, 0x7c, 0x3b, 0x7c, 0x58, 0xe9, 0x61, 0x2d, 0x57, 0xd9, 0x51,
	0xe4, 0x0c, 0x14, 0x28, 0xc2, 0x1b, 0x6f, 0xea, 0x76, 0x75, 0xd5, 0x93, 0x7b, 0x61, 0x35, 0xe9,
	0x33, 0xd3, 0xf4, 0xb8, 0x6e, 0xba, 0x1d, 0x0f, 0xc2, 0xbe, 0x16, 0x4c, 0x47, 0xba, 0xfc, 0xb0,
	0x3f, 0x7b, 0xf6, 0xe1, 0xec, 0xd9, 0xff, 0xce, 0x9e, 0xbd, 0xbb, 0x78, 0xd6, 0xe1, 0xe2, 0x59,
	0x7f, 0x2e, 0x9e, 0xf5, 0xf9, 0xe5, 0x8d, 0x93, 0x6a, 0xef, 0x4a, 0x3b, 0x7c, 0x6f, 0xaf, 0x8d,
	0x3e, 0xb3, 0xf8, 0x81, 0x66, 0x7e, 0x7d, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x5e, 0x72, 0x35,
	0x57, 0x02, 0x00, 0x00,
}

func (m *RewardPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TotalReleased.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LastReleaseTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastReleaseTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTypes(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	if len(m.CommunityPool) > 0 {
		for iNdEx := len(m.CommunityPool) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommunityPool[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RewardPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CommunityPool) > 0 {
		for _, e := range m.CommunityPool {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastReleaseTime)
	n += 1 + l + sovTypes(uint64(l))
	l = m.TotalReleased.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RewardPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommunityPool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommunityPool = append(m.CommunityPool, types.DecCoin{})
			if err := m.CommunityPool[len(m.CommunityPool)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastReleaseTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LastReleaseTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalReleased", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalReleased.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
