// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kiichain/rewards/v1beta1/genesis.proto

package v1beta1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the rewards module's genesis state.
type GenesisState struct {
	// params defines the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// release_schedule has information of how the reward is being released
	ReleaseSchedule ReleaseSchedule `protobuf:"bytes,2,opt,name=release_schedule,json=releaseSchedule,proto3" json:"release_schedule"`
	// reward_pool has information on the community pool
	RewardPool RewardPool `protobuf:"bytes,3,opt,name=reward_pool,json=rewardPool,proto3" json:"reward_pool"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_96ab53dc25b7c542, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetReleaseSchedule() ReleaseSchedule {
	if m != nil {
		return m.ReleaseSchedule
	}
	return ReleaseSchedule{}
}

func (m *GenesisState) GetRewardPool() RewardPool {
	if m != nil {
		return m.RewardPool
	}
	return RewardPool{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "kiichain.rewards.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("kiichain/rewards/v1beta1/genesis.proto", fileDescriptor_96ab53dc25b7c542)
}

var fileDescriptor_96ab53dc25b7c542 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0xe3, 0xef, 0x43, 0x1d, 0x5c, 0x24, 0x50, 0xc4, 0x10, 0x75, 0x30, 0x15, 0x2a, 0x08,
	0x16, 0x5b, 0x05, 0x66, 0x06, 0x16, 0x06, 0x24, 0x54, 0xb5, 0x5b, 0x97, 0xca, 0x49, 0x8f, 0x52,
	0x8b, 0x34, 0x27, 0xb2, 0x5d, 0x7e, 0xee, 0x82, 0xcb, 0xea, 0xd8, 0x91, 0x09, 0xa1, 0xe4, 0x22,
	0x58, 0x51, 0x1d, 0x37, 0x88, 0x21, 0x6c, 0xce, 0xc9, 0xf3, 0x3e, 0xe7, 0xe8, 0xa5, 0x67, 0x8f,
	0x4a, 0x25, 0x0b, 0xa9, 0x72, 0xa1, 0xe1, 0x59, 0xea, 0xb9, 0x11, 0x4f, 0xc3, 0x18, 0xac, 0x1c,
	0x8a, 0x14, 0x72, 0x30, 0xca, 0xf0, 0x42, 0xa3, 0xc5, 0x30, 0xda, 0x71, 0xdc, 0x73, 0xdc, 0x73,
	0xbd, 0xa3, 0x14, 0x53, 0x74, 0x90, 0xd8, 0xbe, 0x6a, 0xbe, 0xc7, 0x12, 0x34, 0x4b, 0x34, 0x22,
	0x96, 0x06, 0x1a, 0x65, 0x82, 0x2a, 0xf7, 0xff, 0x4f, 0x5b, 0xf7, 0x16, 0x52, 0xcb, 0xa5, 0x5f,
	0xdb, 0x1b, 0xb4, 0x62, 0xf6, 0xb5, 0x00, 0x4f, 0x9d, 0x7c, 0x11, 0xba, 0x7f, 0x57, 0x9f, 0x3b,
	0xb1, 0xd2, 0x42, 0x78, 0x43, 0x3b, 0xb5, 0x26, 0x22, 0x7d, 0x72, 0xde, 0xbd, 0xec, 0xf3, 0xb6,
	0xf3, 0xf9, 0xc8, 0x71, 0xb7, 0x7b, 0xeb, 0x8f, 0xe3, 0x60, 0xec, 0x53, 0xe1, 0x94, 0x1e, 0x6a,
	0xc8, 0x40, 0x1a, 0x98, 0x99, 0x64, 0x01, 0xf3, 0x55, 0x06, 0xd1, 0x3f, 0x67, 0xba, 0x68, 0x37,
	0x8d, 0xeb, 0xc4, 0xc4, 0x07, 0xbc, 0xf2, 0x40, 0xff, 0x1e, 0x87, 0xf7, 0xb4, 0x5b, 0x27, 0x67,
	0x05, 0x62, 0x16, 0xfd, 0x77, 0xda, 0xc1, 0x5f, 0xda, 0xed, 0xf7, 0x08, 0x31, 0xf3, 0x46, 0xaa,
	0x7f, 0x26, 0x0f, 0xeb, 0x92, 0x91, 0x4d, 0xc9, 0xc8, 0x67, 0xc9, 0xc8, 0x5b, 0xc5, 0x82, 0x4d,
	0xc5, 0x82, 0xf7, 0x8a, 0x05, 0xd3, 0xeb, 0x54, 0xd9, 0xc5, 0x2a, 0xe6, 0x09, 0x2e, 0x45, 0x53,
	0x62, 0xf3, 0x78, 0x69, 0xfa, 0x74, 0x3d, 0xee, 0x5a, 0x8d, 0x3b, 0xae, 0xd0, 0xab, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb7, 0xe4, 0x62, 0x5c, 0x17, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RewardPool.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.ReleaseSchedule.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.ReleaseSchedule.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.RewardPool.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleaseSchedule", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReleaseSchedule.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardPool.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
