// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kiichain/rewards/v1beta1/types.proto

package v1beta1

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ReleaseSchedule defines information related to reward distribution
type ReleaseSchedule struct {
	// Total amount to be rewarded
	TotalAmount types.Coin `protobuf:"bytes,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount" yaml:"total_amount"`
	// Amount released
	ReleasedAmount types.Coin `protobuf:"bytes,2,opt,name=released_amount,json=releasedAmount,proto3" json:"released_amount" yaml:"released_amount"`
	// Timestamp of end of release
	EndTime time.Time `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time" yaml:"end_time"`
	// Last height released
	LastReleaseTime time.Time `protobuf:"bytes,5,opt,name=last_release_time,json=lastReleaseTime,proto3,stdtime" json:"last_release_time" yaml:"last_release_time"`
	// If reward pool is active
	Active bool `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty" yaml:"active"`
}

func (m *ReleaseSchedule) Reset()         { *m = ReleaseSchedule{} }
func (m *ReleaseSchedule) String() string { return proto.CompactTextString(m) }
func (*ReleaseSchedule) ProtoMessage()    {}
func (*ReleaseSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_890c6773eb163743, []int{0}
}
func (m *ReleaseSchedule) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReleaseSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReleaseSchedule.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReleaseSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseSchedule.Merge(m, src)
}
func (m *ReleaseSchedule) XXX_Size() int {
	return m.Size()
}
func (m *ReleaseSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseSchedule proto.InternalMessageInfo

func (m *ReleaseSchedule) GetTotalAmount() types.Coin {
	if m != nil {
		return m.TotalAmount
	}
	return types.Coin{}
}

func (m *ReleaseSchedule) GetReleasedAmount() types.Coin {
	if m != nil {
		return m.ReleasedAmount
	}
	return types.Coin{}
}

func (m *ReleaseSchedule) GetEndTime() time.Time {
	if m != nil {
		return m.EndTime
	}
	return time.Time{}
}

func (m *ReleaseSchedule) GetLastReleaseTime() time.Time {
	if m != nil {
		return m.LastReleaseTime
	}
	return time.Time{}
}

func (m *ReleaseSchedule) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

// RewardPool is the global fee pool for distribution.
type RewardPool struct {
	CommunityPool github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,1,rep,name=community_pool,json=communityPool,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"community_pool"`
}

func (m *RewardPool) Reset()         { *m = RewardPool{} }
func (m *RewardPool) String() string { return proto.CompactTextString(m) }
func (*RewardPool) ProtoMessage()    {}
func (*RewardPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_890c6773eb163743, []int{1}
}
func (m *RewardPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardPool.Merge(m, src)
}
func (m *RewardPool) XXX_Size() int {
	return m.Size()
}
func (m *RewardPool) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardPool.DiscardUnknown(m)
}

var xxx_messageInfo_RewardPool proto.InternalMessageInfo

func (m *RewardPool) GetCommunityPool() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.CommunityPool
	}
	return nil
}

func init() {
	proto.RegisterType((*ReleaseSchedule)(nil), "kiichain.rewards.v1beta1.ReleaseSchedule")
	proto.RegisterType((*RewardPool)(nil), "kiichain.rewards.v1beta1.RewardPool")
}

func init() {
	proto.RegisterFile("kiichain/rewards/v1beta1/types.proto", fileDescriptor_890c6773eb163743)
}

var fileDescriptor_890c6773eb163743 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xb1, 0x8e, 0xd3, 0x4c,
	0x10, 0xc7, 0xb3, 0x5f, 0xf4, 0x85, 0xd3, 0x86, 0xbb, 0x28, 0x06, 0x21, 0x13, 0x90, 0x1d, 0x59,
	0x57, 0x04, 0x10, 0x6b, 0xdd, 0x41, 0x81, 0xe8, 0x08, 0xd4, 0x08, 0x19, 0x1a, 0x68, 0xa2, 0xb5,
	0xbd, 0x38, 0xab, 0xdb, 0xf5, 0x44, 0xd9, 0xf5, 0x41, 0x0a, 0x9e, 0x80, 0xe6, 0x1e, 0x03, 0x51,
	0xf1, 0x02, 0xf4, 0x57, 0x5e, 0x49, 0x95, 0x43, 0x49, 0x41, 0x7f, 0x4f, 0x80, 0xbc, 0xbb, 0xb6,
	0x4e, 0x80, 0x74, 0x8d, 0xbd, 0x33, 0x9a, 0xf9, 0xfd, 0xc7, 0x7f, 0xcf, 0xe2, 0xfd, 0x23, 0xce,
	0xb3, 0x39, 0xe5, 0x65, 0xbc, 0x64, 0x1f, 0xe8, 0x32, 0x57, 0xf1, 0xf1, 0x41, 0xca, 0x34, 0x3d,
	0x88, 0xf5, 0x6a, 0xc1, 0x14, 0x59, 0x2c, 0x41, 0x83, 0xe7, 0x37, 0x55, 0xc4, 0x55, 0x11, 0x57,
	0x35, 0x0a, 0x32, 0x50, 0x12, 0x54, 0x9c, 0x52, 0xc5, 0xda, 0xd6, 0x0c, 0x78, 0x69, 0x3b, 0x47,
	0x37, 0x0b, 0x28, 0xc0, 0x1c, 0xe3, 0xfa, 0xe4, 0xb2, 0x61, 0x01, 0x50, 0x08, 0x16, 0x9b, 0x28,
	0xad, 0xde, 0xc7, 0x9a, 0x4b, 0xa6, 0x34, 0x95, 0x0b, 0x57, 0x30, 0xa4, 0x92, 0x97, 0x10, 0x9b,
	0xa7, 0x4d, 0x45, 0xdf, 0xbb, 0x78, 0x90, 0x30, 0xc1, 0xa8, 0x62, 0xaf, 0xb3, 0x39, 0xcb, 0x2b,
	0xc1, 0xbc, 0xb7, 0xf8, 0xba, 0x06, 0x4d, 0xc5, 0x8c, 0x4a, 0xa8, 0x4a, 0xed, 0xa3, 0x31, 0x9a,
	0xf4, 0x0f, 0x6f, 0x13, 0x3b, 0x14, 0xa9, 0x87, 0x6a, 0x26, 0x25, 0xcf, 0x81, 0x97, 0xd3, 0x3b,
	0xa7, 0xeb, 0xb0, 0x73, 0xb1, 0x0e, 0x6f, 0xac, 0xa8, 0x14, 0x4f, 0xa3, 0xcb, 0xcd, 0x51, 0xd2,
	0x37, 0xe1, 0x33, 0x13, 0x79, 0x29, 0x1e, 0x2c, 0xad, 0x5a, 0xde, 0xd0, 0xff, 0xbb, 0x8a, 0x1e,
	0x38, 0xfa, 0x2d, 0x4b, 0xff, 0xa3, 0x3f, 0x4a, 0xf6, 0x9a, 0x8c, 0xd3, 0x48, 0xf0, 0x0e, 0x2b,
	0xf3, 0x59, 0xfd, 0xf1, 0x7e, 0xd7, 0xc0, 0x47, 0xc4, 0x3a, 0x43, 0x1a, 0x67, 0xc8, 0x9b, 0xc6,
	0x99, 0x76, 0xf6, 0x81, 0xa5, 0x37, 0x9d, 0xd1, 0xc9, 0x79, 0x88, 0x92, 0x6b, 0xac, 0xcc, 0xeb,
	0x52, 0x4f, 0xe0, 0xa1, 0xa0, 0x4a, 0xcf, 0x9c, 0x94, 0x85, 0xff, 0x7f, 0x25, 0x7c, 0xdf, 0xc1,
	0x7d, 0x0b, 0xff, 0x0b, 0x61, 0x55, 0x06, 0x75, 0xde, 0xfd, 0x04, 0xa3, 0x76, 0x0f, 0xf7, 0x68,
	0xa6, 0xf9, 0x31, 0xf3, 0x7b, 0x63, 0x34, 0xd9, 0x99, 0x0e, 0x2f, 0xd6, 0xe1, 0xae, 0x45, 0xd8,
	0x7c, 0x94, 0xb8, 0x82, 0xe8, 0x33, 0xc2, 0x38, 0x31, 0xdb, 0xf3, 0x0a, 0x40, 0x78, 0x9f, 0xf0,
	0x5e, 0x06, 0x52, 0x56, 0x25, 0xd7, 0xab, 0xd9, 0x02, 0x40, 0xf8, 0x68, 0xdc, 0x9d, 0xf4, 0x0f,
	0xef, 0xfe, 0xd3, 0xde, 0x17, 0x2c, 0x33, 0x0e, 0x3f, 0xa9, 0xc7, 0xfc, 0x7a, 0x1e, 0x3e, 0x28,
	0xb8, 0x9e, 0x57, 0x29, 0xc9, 0x40, 0xc6, 0x6e, 0x03, 0xed, 0xeb, 0xa1, 0xca, 0x8f, 0xdc, 0xea,
	0xba, 0x1e, 0xf5, 0xe5, 0xd7, 0xb7, 0xfb, 0x28, 0xd9, 0x6d, 0xd5, 0x6a, 0xf9, 0xe9, 0xcb, 0xd3,
	0x4d, 0x80, 0xce, 0x36, 0x01, 0xfa, 0xb9, 0x09, 0xd0, 0xc9, 0x36, 0xe8, 0x9c, 0x6d, 0x83, 0xce,
	0x8f, 0x6d, 0xd0, 0x79, 0xf7, 0xf8, 0x12, 0xba, 0xbd, 0x1c, 0xed, 0xe1, 0x63, 0x7b, 0x4f, 0x8c,
	0x48, 0xb3, 0xf2, 0x69, 0xcf, 0x78, 0xfa, 0xe8, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x7e,
	0x42, 0xeb, 0x50, 0x03, 0x00, 0x00,
}

func (m *ReleaseSchedule) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReleaseSchedule) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReleaseSchedule) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LastReleaseTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastReleaseTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTypes(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.EndTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTypes(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.ReleasedAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.TotalAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *RewardPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommunityPool) > 0 {
		for iNdEx := len(m.CommunityPool) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommunityPool[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReleaseSchedule) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalAmount.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.ReleasedAmount.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LastReleaseTime)
	n += 1 + l + sovTypes(uint64(l))
	if m.Active {
		n += 2
	}
	return n
}

func (m *RewardPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CommunityPool) > 0 {
		for _, e := range m.CommunityPool {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReleaseSchedule) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReleaseSchedule: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReleaseSchedule: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleasedAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReleasedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastReleaseTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LastReleaseTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RewardPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommunityPool", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommunityPool = append(m.CommunityPool, types.DecCoin{})
			if err := m.CommunityPool[len(m.CommunityPool)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
