name: Lint

on:
  push:
    branches:
      - main
      - release/**
      - feat/**
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true

      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=30m
          version: v2.7.2
